### ISSUE TITLE
No way to see the version in the program

### ISSUE THREAD

**Issue by Zamiell** [necrommunity/macsg#13]
I just had the following conversation with a friend.

"Hey, what version of MacSG do you have installed?"
"I have no idea. How do I find out?"
"Well, sometimes its just in the title of the program."
"It's definitely not in the title; it just says 'MacSG'."
"Well, try choosing 'Help' from the menu, and then clicking 'About'."
"There's no 'Help' or 'About' in the menu."
"Ok, maybe there's some file in the directory where its installed."
"Well, I looked in 'C:\Program Files (x86)\MacSG', and there was nothing in there except for a 'MacSG.exe.config' file, and there was no version information in there."
[10 frustrating minutes later]
"Ok, I found it, you have to open "Add/Remove Programs" and look for MacSG in there."
"Wow. That's pretty ridiculous."

It would be great if you could just put the version number in the title. ;)

**Comment by MacND** [comment]
Resolved in version [0.9.3.1](https://github.com/necrommunity/macsg/releases/tag/0.9.3.1) via PR #15
